name: Build
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake fakeroot build-essential debhelper

      - name: Building elf2vkp
        run: |
          fakeroot debian/rules binary
          fakeroot debian/rules clean
          cmake -B build -DBUILD_STATIC:BOOL=TRUE -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)
          cd build
          tar -cpvzf elf2vkp.tar.gz ./elf2vkp

      - name: Update Homebrew Formula
        uses: izumin5210/action-homebrew-tap@releases/v0
        with:
          tap: siemens-mobile-hacks/homebrew-tap
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.TAP_GITHUB_TOKEN }}
          release-branch: main
          formula: elf2vkp.rb
          commit-message: Brew formula update for elf2vkp version ${{ env.RELEASE_VERSION }}

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ../*.deb
            build/elf2vkp.tar.gz

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Building elf2vkp
        run: |
          cmake -B build
          cmake --build build --config Release

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            build/Release/elf2vkp.exe
