name: Build
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake fakeroot build-essential debhelper

      - name: Building elf2vkp
        run: |
          fakeroot debian/rules binary
          fakeroot debian/rules clean
          cmake -B build -DBUILD_STATIC:BOOL=TRUE -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)
          cd build
          tar -cpvzf elf2vkp.tar.gz ./elf2vkp

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ../*.deb
            build/elf2vkp.tar.gz

      - name: Check out homebrew tap
        uses: actions/checkout@v3
        with:
          repository: siemens-mobile-hacks/homebrew-tap
          path: ./tap
          token: ${{ secrets.TAP_GITHUB_TOKEN }}

      - name: Generate formula
        run: |
          sed -i "s/RELEASE_TAG_NAME/$GITHUB_REF_NAME/g" elf2vkp.rb
          sed -i "s/RELEASE_TAG_HASH/$GITHUB_SHA/g" elf2vkp.rb
          cat elf2vkp.rb

          cd tap
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          cp ../elf2vkp.rb Formula/elf2vkp.rb
          git add Formula/elf2vkp.rb
          git commit -m "elf2vkp: $GITHUB_REF_NAME"
          git push --set-upstream origin main

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Building elf2vkp
        run: |
          cmake -B build
          cmake --build build --config Release

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            build/Release/elf2vkp.exe
