name: Build
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake fakeroot build-essential debhelper

      - name: Building elf2vkp
        run: |
          fakeroot debian/rules binary
          fakeroot debian/rules clean
          cmake -B build -DBUILD_STATIC:BOOL=TRUE
          cmake --build build --config Release -j$(nproc)
          cd build
          tar -cpvzf elf2vkp.tar.gz ./elf2vkp

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ../*.deb
            build/elf2vkp.tar.gz

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Building elf2vkp
        run: |
          cmake -B build
          cmake --build build --config Release

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            build/Release/elf2vkp.exe
